
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADJECTIVE ADVERB CONJUNCTION DETERMINER NOUN PREPOSITION PRONOUN VERBsentence : subject predicate\n                | subject predicate conjunction sentence\n                | subject predicate prepositional_phrase\n                | subject predicate prepositional_phrase conjunction sentencesubject : noun_phrase\n               | PRONOUNpredicate : verb_phrase\n                 | verb_phrase object\n                 | verb_phrase adverb_phrase\n                 | verb_phrase prepositional_phraseobject : noun_phraseprepositional_phrase : PREPOSITION noun_phraseadverb_phrase : ADVERB\n                     | ADVERB ADVERBnoun_phrase : NOUN\n                   | DETERMINER NOUN\n                   | DETERMINER ADJECTIVE NOUN\n                   | ADJECTIVE NOUNverb_phrase : VERB\n                   | VERB noun_phrase\n                   | VERB noun_phrase prepositional_phraseconjunction : CONJUNCTION'
    
_lr_action_items = {'PRONOUN':([0,14,16,26,],[4,4,-22,4,]),'NOUN':([0,5,6,7,9,10,11,12,13,14,16,17,23,24,26,27,29,],[5,-15,11,13,5,5,-16,24,-18,5,-22,5,-20,-17,5,-12,-21,]),'DETERMINER':([0,5,9,10,11,13,14,16,17,23,24,26,27,29,],[6,-15,6,6,-16,-18,6,-22,6,-20,-17,6,-12,-21,]),'ADJECTIVE':([0,5,6,9,10,11,13,14,16,17,23,24,26,27,29,],[7,-15,12,7,7,-16,-18,7,-22,7,-20,-17,7,-12,-21,]),'$end':([1,5,8,9,10,11,13,15,18,19,20,21,22,23,24,25,27,28,29,30,],[0,-15,-1,-7,-19,-16,-18,-3,-8,-9,-10,-11,-13,-20,-17,-2,-12,-14,-21,-4,]),'VERB':([2,3,4,5,11,13,24,],[10,-5,-6,-15,-16,-18,-17,]),'CONJUNCTION':([5,8,9,10,11,13,15,18,19,20,21,22,23,24,27,28,29,],[-15,16,-7,-19,-16,-18,16,-8,-9,-10,-11,-13,-20,-17,-12,-14,-21,]),'PREPOSITION':([5,8,9,10,11,13,18,19,20,21,22,23,24,27,28,29,],[-15,17,17,-19,-16,-18,-8,-9,-10,-11,-13,17,-17,-12,-14,-21,]),'ADVERB':([5,9,10,11,13,22,23,24,27,29,],[-15,22,-19,-16,-18,28,-20,-17,-12,-21,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'sentence':([0,14,26,],[1,25,30,]),'subject':([0,14,26,],[2,2,2,]),'noun_phrase':([0,9,10,14,17,26,],[3,21,23,3,27,3,]),'predicate':([2,],[8,]),'verb_phrase':([2,],[9,]),'conjunction':([8,15,],[14,26,]),'prepositional_phrase':([8,9,23,],[15,20,29,]),'object':([9,],[18,]),'adverb_phrase':([9,],[19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> sentence","S'",1,None,None,None),
  ('sentence -> subject predicate','sentence',2,'p_sentence','anotherthing.py',47),
  ('sentence -> subject predicate conjunction sentence','sentence',4,'p_sentence','anotherthing.py',48),
  ('sentence -> subject predicate prepositional_phrase','sentence',3,'p_sentence','anotherthing.py',49),
  ('sentence -> subject predicate prepositional_phrase conjunction sentence','sentence',5,'p_sentence','anotherthing.py',50),
  ('subject -> noun_phrase','subject',1,'p_subject','anotherthing.py',54),
  ('subject -> PRONOUN','subject',1,'p_subject','anotherthing.py',55),
  ('predicate -> verb_phrase','predicate',1,'p_predicate','anotherthing.py',59),
  ('predicate -> verb_phrase object','predicate',2,'p_predicate','anotherthing.py',60),
  ('predicate -> verb_phrase adverb_phrase','predicate',2,'p_predicate','anotherthing.py',61),
  ('predicate -> verb_phrase prepositional_phrase','predicate',2,'p_predicate','anotherthing.py',62),
  ('object -> noun_phrase','object',1,'p_object','anotherthing.py',66),
  ('prepositional_phrase -> PREPOSITION noun_phrase','prepositional_phrase',2,'p_prepositional_phrase','anotherthing.py',70),
  ('adverb_phrase -> ADVERB','adverb_phrase',1,'p_adverb_phrase','anotherthing.py',74),
  ('adverb_phrase -> ADVERB ADVERB','adverb_phrase',2,'p_adverb_phrase','anotherthing.py',75),
  ('noun_phrase -> NOUN','noun_phrase',1,'p_noun_phrase','anotherthing.py',79),
  ('noun_phrase -> DETERMINER NOUN','noun_phrase',2,'p_noun_phrase','anotherthing.py',80),
  ('noun_phrase -> DETERMINER ADJECTIVE NOUN','noun_phrase',3,'p_noun_phrase','anotherthing.py',81),
  ('noun_phrase -> ADJECTIVE NOUN','noun_phrase',2,'p_noun_phrase','anotherthing.py',82),
  ('verb_phrase -> VERB','verb_phrase',1,'p_verb_phrase','anotherthing.py',86),
  ('verb_phrase -> VERB noun_phrase','verb_phrase',2,'p_verb_phrase','anotherthing.py',87),
  ('verb_phrase -> VERB noun_phrase prepositional_phrase','verb_phrase',3,'p_verb_phrase','anotherthing.py',88),
  ('conjunction -> CONJUNCTION','conjunction',1,'p_conjunction','anotherthing.py',92),
]
